const config = {
    content: ["./index.html", "./src/**/*.{js,jsx}"],
    theme: {
        extend: {
            colors: {
                background: "#f9f9f9",
                surface: "#f9f9f9",
                "surface-bright": "#f9f9f9",
                "surface-dim": "#dadada",
                "surface-container-lowest": "#ffffff",
                "surface-container-low": "#f3f3f3",
                "surface-container": "#eeeeee",
                "surface-container-high": "#e8e8e8",
                "surface-container-highest": "#e2e2e2",
                "surface-variant": "#e2e2e2",
                "surface-tint": "#1b6d24",
                primary: "#0d631b",
                "primary-container": "#2e7d32",
                "primary-fixed": "#a3f69c",
                "primary-fixed-dim": "#88d982",
                secondary: "#75584d",
                "secondary-container": "#fed7ca",
                "secondary-fixed": "#ffdbce",
                "secondary-fixed-dim": "#e4beb2",
                tertiary: "#8e3d00",
                "tertiary-container": "#b45000",
                "tertiary-fixed": "#ffdbca",
                "tertiary-fixed-dim": "#ffb68f",
                outline: "#707a6c",
                "outline-variant": "#bfcaba",
                error: "#ba1a1a",
                "error-container": "#ffdad6",
                "on-background": "#1a1c1c",
                "on-surface": "#1a1c1c",
                "on-surface-variant": "#40493d",
                "on-primary": "#ffffff",
                "on-primary-container": "#cbffc2",
                "on-primary-fixed": "#002204",
                "on-primary-fixed-variant": "#005312",
                "on-secondary": "#ffffff",
                "on-secondary-container": "#795c51",
                "on-secondary-fixed": "#2b160f",
                "on-secondary-fixed-variant": "#5b4137",
                "on-tertiary": "#ffffff",
                "on-tertiary-container": "#ffeee6",
                "on-tertiary-fixed": "#331200",
                "on-tertiary-fixed-variant": "#773200",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "inverse-surface": "#2f3131",
                "inverse-on-surface": "#f0f1f1",
                "inverse-primary": "#88d982",
            },
            fontFamily: {
                headline: ["'Be Vietnam Pro'", "sans-serif"],
                body: ["'Be Vietnam Pro'", "sans-serif"],
                label: ["Inter", "sans-serif"],
            },
            borderRadius: {
                xl: "0.75rem",
                "2xl": "1.25rem",
                "3xl": "1.75rem",
            },
            boxShadow: {
                ambient: "0px 20px 40px rgba(26, 28, 28, 0.06)",
            },
            backgroundImage: {
                "primary-glow": "linear-gradient(135deg, rgba(13, 99, 27, 1), rgba(46, 125, 50, 1))",
            },
            screens: {
                xs: "480px",
            },
        },
    },
    plugins: [],
};
export default config;
